<%@ Page Title="POC SignalR" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="SignaRTest.aspx.cs" Inherits="WebFormSandBox.SignaRTest" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <script src="Scripts/jquery-3.4.1.min.js"></script>
    <script src="Scripts/jquery.signalR-2.4.1.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <script type="text/javascript">

        //$(function () {

        //    var logger = $.connection.logHub;

        //    logger.client.logMessage = function (msg) {

        //        $("#logUl").append("<li>" + msg + "</li>");
        //    };

        //    $.connection.hub.start();
        //});

        $(function () {
            // Declare a proxy to reference the hub.
            var chat = $.connection.chatHub;
            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message.
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page.
                $('#discussion').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    msg = $('#message').val();
                    // Call the Send method on the hub.
                    chat.server.send($('#displayname').val(), msg);
                    // Clear text box and reset focus for next comment.
                    $('#message').val('').focus();
                    $('#txtDebug').text(msg);
                });
            });
        });

    </script>

    <div>
        <h3>Chat from <%= GetBrowserInfo()%></h3>
        <br />

        <div id="dvChat" class="container">
            <label id="txtDebug" runat="server" style="background-color: lightgoldenrodyellow; width: 100px">....</label>
            <br />
            <br />
            <input type="text" id="message" runat="server" />
            <input type="button" id="sendmessage" value="Send" runat="server" />
            <input type="hidden" id="displayname" />
            <ul id="discussion">
            </ul>
        </div>

        <h3>Log Items from server</h3>

<%--        <div style="overflow: auto; height: 300px;">
            <asp:ListView ID="logListView" runat="server"
                ItemPlaceholderID="itemPlaceHolder"
                ClientIDMode="Static" EnableViewState="false">
                <LayoutTemplate>
                    <ul id="logUl">
                        <li runat="server"
                            id="itemPlaceHolder"></li>
                    </ul>
                </LayoutTemplate>
                <ItemTemplate>
                    <li><span class="logItem">
                        <%#Container.DataItem.ToString() %></span></li>
                </ItemTemplate>
            </asp:ListView>
        </div>--%>

    </div>

</asp:Content>
